### PR TITLE
TASK: introduce prototype for pagination parameters

### PR DESCRIPTION
**Pull request by davidspiola**
With this new prototype is quite easy to register additional parameters in a custom implementation. eg. taxonomies or date filters

### CODE REVIEW

**Comment by dimaip** [comment]
Wow, I like the idea! Can you please add some info to the readme?

**Comment by davidspiola** [comment]
Will do! BTW: One more thing that might need some adjustment is the entryDiscriminator. For now I just extended it with the new parameter. But I think, that's not a good strategy. Any ideas?

**Comment by dimaip** [comment]
Why not? It just provides some defaults, of course it would need to be adjusted for other usecases.

**Comment by davidspiola** [comment]
Alright, I updated the readme

**Comment by davidspiola** [comment]
@dimaip do you think the pull request is ready to merge?

**Comment by dimaip** [comment]
Yup thank you!

**Pull request merged**
